name: 📝 Task
description: Track a specific task or sub-task for the Luxafor Controller roadmap
title: "[Task]: "
labels: ["task"]
assignees: ["@smcnab1"]

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done? Keep it short and actionable.
      placeholder: e.g. "Add support for startup colour preference (restore last colour on launch)"
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Milestone
      description: Which Luxafor Controller version does this task belong to?
      options:
        - 1.1.0 — Preferences & Shortcuts
        - 1.2.0 — Quick Actions & Menubar
        - 1.3.0 — Presets & Schedules
        - 1.4.0 — Device Enhancements
        - 1.5.0 — Integrations & Automation
        - Backlog / Ideas
        - Technical Improvements
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Add more context, notes, or references if needed.
      placeholder: Steps, design notes, device API considerations, or UI/UX notes
    validations:
      required: false

  - type: textarea
    id: checklist
    attributes:
      label: Checklist
      description: Break the task into sub-steps if useful.
      value: |
        - [ ] Step 1
        - [ ] Step 2
        - [ ] Step 3
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - Low
        - Medium
        - High
    validations:
      required: false